// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DirExists(arg1) {
  return window['go']['main']['App']['DirExists'](arg1);
}

export function Os() {
  return window['go']['main']['App']['Os']();
}
